version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: library-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: library
    volumes:
      - mongodb_data:/data/db
    networks:
      - library-network

  redis:
    image: redis:7.2-alpine
    container_name: library-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - library-network

  app:
    build: .
    container_name: library-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/library
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - library-network

volumes:
  mongodb_data:
  redis_data:

networks:
  library-network:
    driver: bridge
